# What is tuple? Difference between list and tuple.
--> tuple is collection of similar or different data type.
    tuple is immutable.
    tuple is ordered collection.
    tuple defined in circle brackets ().
Difference between list and tuple :
 1>   list is mutable.
      tuple is immutable.   
 2>   The implication of iterations is Time-consuming
      The implication of iterations is comparatively Faster
 3>   Lists consume more memory
      Tuple consumes less memory as compared to the list
 4>   Lists have several built-in methods
      Tuple does not have many built-in methods.                  