# How will you set the starting value in generating random numbers?
Description
Python number method seed() sets the integer starting value used in generating random numbers. Call this function before calling any other random module function.

Syntax
Following is the syntax for seed() method −

seed ( [x] )
Note − This function is not accessible directly, so we need to import the random module and then we need to call this function using random static object.

Parameters
x − This is the seed for the next random number. If omitted, then it takes system time to generate next random number.

Return Value
This method does not return any value.